set(VCPKG_TARGET_ARCHITECTURE ppc64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME AIX)
set(VCPKG_C_FLAGS "-march=ppc64")
set(VCPKG_CXX_FLAGS "-march=ppc64")
set(VCPKG_LINKER_FLAGS "-march=ppc64")
